# Generated by Django 5.1.1 on 2024-09-06 15:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('updated', models.DateTimeField(verbose_name='date updated')),
                ('name', models.CharField(max_length=50)),
                ('stat_cost', models.CharField(max_length=10, null=True)),
                ('stat', models.CharField(max_length=15, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('I', 'Inability'), ('P', 'Practiced'), ('T', 'Trained'), ('S', 'Specialized')], default='T', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='I18NCode',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='I18NCountryCode',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('updated', models.DateTimeField(verbose_name='date updated')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('updated', models.DateTimeField(verbose_name='date updated')),
                ('name', models.CharField(max_length=50)),
                ('might_start', models.PositiveSmallIntegerField()),
                ('speed_start', models.PositiveSmallIntegerField()),
                ('intellect_start', models.PositiveSmallIntegerField()),
                ('might_edge_start', models.PositiveSmallIntegerField(default=0)),
                ('speed_edge_start', models.PositiveSmallIntegerField(default=0)),
                ('intellect_edge_start', models.PositiveSmallIntegerField(default=0)),
                ('cyphers_start', models.PositiveSmallIntegerField(default=2)),
                ('abilities_tier1', models.ManyToManyField(related_name='charactertype_ab_1s', related_query_name='charactertype_ab_1', to='cscg.ability')),
                ('abilities_tier2', models.ManyToManyField(related_name='charactertype_ab_2s', related_query_name='charactertype_ab_2', to='cscg.ability')),
                ('abilities_tier3', models.ManyToManyField(related_name='charactertype_ab_3s', related_query_name='charactertype_ab_3', to='cscg.ability')),
                ('abilities_tier4', models.ManyToManyField(related_name='charactertype_ab_4s', related_query_name='charactertype_ab_4', to='cscg.ability')),
                ('abilities_tier5', models.ManyToManyField(related_name='charactertype_ab_5s', related_query_name='charactertype_ab_5', to='cscg.ability')),
                ('abilities_tier6', models.ManyToManyField(related_name='charactertype_ab_6s', related_query_name='charactertype_ab_6', to='cscg.ability')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('updated', models.DateTimeField(verbose_name='date updated')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('abilities', models.ManyToManyField(to='cscg.ability')),
                ('skills', models.ManyToManyField(to='cscg.characterskill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('updated', models.DateTimeField(verbose_name='date updated')),
                ('name', models.CharField(max_length=50)),
                ('abilities_tier1', models.ManyToManyField(related_name='flavor_ab_1s', related_query_name='flavor_ab_1', to='cscg.ability')),
                ('abilities_tier2', models.ManyToManyField(related_name='flavor_ab_2s', related_query_name='flavor_ab_2', to='cscg.ability')),
                ('abilities_tier3', models.ManyToManyField(related_name='flavor_ab_3s', related_query_name='flavor_ab_3', to='cscg.ability')),
                ('abilities_tier4', models.ManyToManyField(related_name='flavor_ab_4s', related_query_name='flavor_ab_4', to='cscg.ability')),
                ('abilities_tier5', models.ManyToManyField(related_name='flavor_ab_5s', related_query_name='flavor_ab_5', to='cscg.ability')),
                ('abilities_tier6', models.ManyToManyField(related_name='flavor_ab_6s', related_query_name='flavor_ab_6', to='cscg.ability')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('updated', models.DateTimeField(verbose_name='date updated')),
                ('name', models.CharField(max_length=50)),
                ('abilities_tier1', models.ManyToManyField(related_name='focus_ab_1s', related_query_name='focus_ab_1', to='cscg.ability')),
                ('abilities_tier2', models.ManyToManyField(related_name='focus_ab_2s', related_query_name='focus_ab_2', to='cscg.ability')),
                ('abilities_tier3', models.ManyToManyField(related_name='focus_ab_3s', related_query_name='focus_ab_3', to='cscg.ability')),
                ('abilities_tier4', models.ManyToManyField(related_name='focus_ab_4s', related_query_name='focus_ab_4', to='cscg.ability')),
                ('abilities_tier5', models.ManyToManyField(related_name='focus_ab_5s', related_query_name='focus_ab_5', to='cscg.ability')),
                ('abilities_tier6', models.ManyToManyField(related_name='focus_ab_6s', related_query_name='focus_ab_6', to='cscg.ability')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('updated', models.DateTimeField(verbose_name='date updated')),
                ('name', models.CharField(max_length=50)),
                ('tier', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('might', models.PositiveSmallIntegerField(default=0)),
                ('speed', models.PositiveSmallIntegerField(default=0)),
                ('intellect', models.PositiveSmallIntegerField(default=0)),
                ('might_edge', models.PositiveSmallIntegerField(default=0)),
                ('speed_edge', models.PositiveSmallIntegerField(default=0)),
                ('intellect_edge', models.PositiveSmallIntegerField(default=0)),
                ('cyphers', models.PositiveSmallIntegerField(default=2)),
                ('abilities', models.ManyToManyField(to='cscg.ability')),
                ('skills', models.ManyToManyField(to='cscg.characterskill')),
                ('character_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cscg.charactertype')),
                ('desciptors', models.ManyToManyField(to='cscg.descriptor')),
                ('flavor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cscg.flavor')),
                ('focus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cscg.focus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='I18NCharField50',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cscg.i18ncode')),
                ('countrycode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cscg.i18ncountrycode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='I18NCharField200',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cscg.i18ncode')),
                ('countrycode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cscg.i18ncountrycode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='I18NCharField20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=20)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cscg.i18ncode')),
                ('countrycode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cscg.i18ncountrycode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='I18NTextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cscg.i18ncode')),
                ('countrycode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cscg.i18ncountrycode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='characterskill',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cscg.skill'),
        ),
    ]
