# Generated by Django 5.1.1 on 2024-09-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
