# Generated by Django 5.1.1 on 2024-09-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscg', '0002_flavor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='focus',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
