# Generated by Django 5.1.1 on 2024-09-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscg', '0003_focus_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='name_en',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
