# Generated by Django 5.1.1 on 2024-09-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscg', '0004_ability_name_en_alter_ability_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='cs_page',
            field=models.IntegerField(default=0),
        ),
    ]
