# Generated by Django 5.1.1 on 2024-09-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscg', '0005_ability_cs_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='stat_cost',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
