# Generated by Django 5.1.1 on 2024-09-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscg', '0007_alter_ability_cs_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='stat',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
