# Generated by Django 5.1.1 on 2024-09-20 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscg', '0008_alter_ability_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='focus',
            name='name_en',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ability',
            name='stat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='focus',
            name='abilities_tier1',
        ),
        migrations.RemoveField(
            model_name='focus',
            name='abilities_tier2',
        ),
        migrations.RemoveField(
            model_name='focus',
            name='abilities_tier3',
        ),
        migrations.RemoveField(
            model_name='focus',
            name='abilities_tier4',
        ),
        migrations.RemoveField(
            model_name='focus',
            name='abilities_tier5',
        ),
        migrations.RemoveField(
            model_name='focus',
            name='abilities_tier6',
        ),
        migrations.CreateModel(
            name='FocusAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abilities', models.ManyToManyField(related_name='focus_abs', related_query_name='focus_ab', to='cscg.ability')),
                ('abilities_to_choose', models.ManyToManyField(related_name='focus_ab_choices', related_query_name='focus_ab_choice', to='cscg.ability')),
            ],
        ),
        migrations.AddField(
            model_name='focus',
            name='abilities_tier1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_ab_1s', related_query_name='focus_ab_1', to='cscg.focusabilities'),
        ),
        migrations.AddField(
            model_name='focus',
            name='abilities_tier2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_ab_2s', related_query_name='focus_ab_2', to='cscg.focusabilities'),
        ),
        migrations.AddField(
            model_name='focus',
            name='abilities_tier3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_ab_3s', related_query_name='focus_ab_3', to='cscg.focusabilities'),
        ),
        migrations.AddField(
            model_name='focus',
            name='abilities_tier4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_ab_4s', related_query_name='focus_ab_4', to='cscg.focusabilities'),
        ),
        migrations.AddField(
            model_name='focus',
            name='abilities_tier5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_ab_5s', related_query_name='focus_ab_5', to='cscg.focusabilities'),
        ),
        migrations.AddField(
            model_name='focus',
            name='abilities_tier6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_ab_6s', related_query_name='focus_ab_6', to='cscg.focusabilities'),
        ),
    ]
