# Generated by Django 5.1.1 on 2024-09-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscg', '0010_initiallink_descriptor_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptor',
            name='cs_page',
            field=models.CharField(default='', max_length=20),
        ),
    ]
