# Generated by Django 5.1.1 on 2024-09-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscg', '0011_descriptor_cs_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptorCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='descriptor',
            name='abilities',
        ),
        migrations.RemoveField(
            model_name='descriptor',
            name='skills',
        ),
        migrations.AddField(
            model_name='descriptor',
            name='characteristics',
            field=models.ManyToManyField(to='cscg.descriptorcharacteristic'),
        ),
    ]
