# Generated by Django 5.1.1 on 2024-09-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscg', '0012_descriptorcharacteristic_remove_descriptor_abilities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='ability',
            name='tier',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ability',
            name='categories',
            field=models.ManyToManyField(to='cscg.abilitycategory'),
        ),
    ]
