# Generated by Django 5.1.1 on 2024-09-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscg', '0013_abilitycategory_ability_tier_ability_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitycategory',
            name='cs_page',
            field=models.CharField(default='', max_length=50),
        ),
    ]
