# Generated by Django 5.1.1 on 2024-09-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscg', '0014_abilitycategory_cs_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitycategory',
            name='name_en',
            field=models.CharField(default='', max_length=50),
        ),
    ]
