# Generated by Django 5.1.1 on 2024-10-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscg', '0015_abilitycategory_name_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cypher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('updated', models.DateTimeField(verbose_name='date updated')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(default='', max_length=50)),
                ('effect', models.TextField(default='')),
                ('hint', models.TextField(default='')),
                ('table', models.TextField(default='')),
                ('level', models.CharField(default='', max_length=10)),
                ('cs_page', models.CharField(default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
