# Generated by Django 5.1.1 on 2024-10-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscg', '0016_cypher'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptor',
            name='is_fantastic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='descriptor',
            name='is_manifeste',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='descriptor',
            name='is_subtle',
            field=models.BooleanField(default=False),
        ),
    ]
