# Generated by Django 5.1.1 on 2024-10-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscg', '0017_descriptor_is_fantastic_descriptor_is_manifeste_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptor',
            name='is_fantastic',
        ),
        migrations.RemoveField(
            model_name='descriptor',
            name='is_manifeste',
        ),
        migrations.RemoveField(
            model_name='descriptor',
            name='is_subtle',
        ),
        migrations.AddField(
            model_name='cypher',
            name='is_fantastic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cypher',
            name='is_manifeste',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cypher',
            name='is_subtle',
            field=models.BooleanField(default=False),
        ),
    ]
