# Generated by Django 5.1.1 on 2024-10-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscg', '0018_remove_descriptor_is_fantastic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cypher',
            name='cs_page',
            field=models.CharField(default='', max_length=50),
        ),
    ]
