# Generated by Django 5.1.1 on 2024-10-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscg', '0019_alter_cypher_cs_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cypher',
            name='cs_page',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cypher',
            name='hint',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='cypher',
            name='table',
            field=models.TextField(default='', null=True),
        ),
    ]
